# Generated by Django 6.0.5 on 2026-05-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('fotos', models.ImageField(upload_to='pets/')),
                ('raca', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[(1, 'Macho'), (2, 'Fêmea')], max_length=20)),
                ('porte', models.CharField(choices=[(1, 'Pequeno'), (2, 'Médio'), (3, 'Grande')], max_length=20)),
                ('vacinado', models.BooleanField(default=False)),
                ('castrado', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[(1, 'Disponível'), (2, 'Adotado'), (3, 'Em Processo')], default=1, max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
