# Generated by Django 6.0.5 on 2026-05-31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('pet', '0002_alter_pet_idade_alter_pet_porte_alter_pet_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='user.user'),
        ),
    ]