# Generated by Django 6.0.5 on 2026-05-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='idade',
            field=models.IntegerField(verbose_name='Idade (meses)'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='porte',
            field=models.CharField(choices=[('1', 'Pequeno'), ('2', 'Médio'), ('3', 'Grande')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('1', 'Macho'), ('2', 'Fêmea')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('1', 'Disponível'), ('2', 'Adotado'), ('3', 'Em Processo')], default='1', max_length=20),
        ),
    ]
