# Generated by Django 6.0.5 on 2026-06-02 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0002_pet_responsavel'),
        ('user', '0002_user_cnpj_ong_user_comprovante_ong_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoDeAdocao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=20)),
                ('mensagem', models.TextField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='user.user')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='pet.pet')),
            ],
            options={
                'ordering': ['-data_solicitacao'],
                'constraints': [models.UniqueConstraint(fields=('adotante', 'pet'), name='solicitacao_unica_por_adotante_pet')],
            },
        ),
    ]
