# Generated by Django 6.0.5 on 2026-05-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_usuario', models.CharField(choices=[('ADOTANTE', 'Adotante'), ('ONG', 'ONG'), ('ADMINISTRADOR', 'Administrador')], default='ADOTANTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
