# Generated by Django 6.0.5 on 2026-06-01 19:58

from django.db import migrations, models


def aprovar_ongs_existentes(apps, schema_editor):
    User = apps.get_model('user', 'User')
    User.objects.filter(tipo_usuario='ONG').update(status_verificacao_ong='APROVADA')


def reverter_aprovacao_ongs_existentes(apps, schema_editor):
    User = apps.get_model('user', 'User')
    User.objects.filter(tipo_usuario='ONG').update(status_verificacao_ong='NAO_SE_APLICA')


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnpj_ong',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='comprovante_ong',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_ongs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='razao_social_ong',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status_verificacao_ong',
            field=models.CharField(choices=[('NAO_SE_APLICA', 'Não se aplica'), ('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='NAO_SE_APLICA', max_length=20),
        ),
        migrations.RunPython(aprovar_ongs_existentes, reverter_aprovacao_ongs_existentes),
    ]
