# Generated by Django 6.0.5 on 2026-06-05 17:54

from django.db import migrations, models


def converter_administradores_para_adotantes(apps, schema_editor):
    User = apps.get_model('user', 'User')
    User.objects.filter(tipo_usuario='ADMINISTRADOR').update(tipo_usuario='ADOTANTE')


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_cnpj_ong_user_comprovante_ong_and_more'),
    ]

    operations = [
        migrations.RunPython(converter_administradores_para_adotantes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADOTANTE', 'Adotante'), ('ONG', 'ONG')], default='ADOTANTE', max_length=20),
        ),
    ]
