TIPO_ADOTANTE = 'ADOTANTE'
TIPO_ONG = 'ONG'

STATUS_ONG_NAO_SE_APLICA = 'NAO_SE_APLICA'
STATUS_ONG_PENDENTE = 'PENDENTE'
STATUS_ONG_APROVADA = 'APROVADA'
STATUS_ONG_REJEITADA = 'REJEITADA'

OPCOES_TIPO_USUARIO = (
    (TIPO_ADOTANTE, 'Adotante'),
    (TIPO_ONG, 'ONG'),
)

OPCOES_STATUS_VERIFICACAO_ONG = (
    (STATUS_ONG_NAO_SE_APLICA, 'Não se aplica'),
    (STATUS_ONG_PENDENTE, 'Pendente'),
    (STATUS_ONG_APROVADA, 'Aprovada'),
    (STATUS_ONG_REJEITADA, 'Rejeitada'),
)
